name: Package WordPress Plugin

on:
  push:
    tags:
      - '*'  # Triggers on all tag pushes (e.g. v1.0.0)

jobs:
  build-and-release:
    name: Zip and upload Plugin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare clean zip folder
        run: |
          mkdir beech_notifications
          shopt -s extglob
          cp -r !(beech_notifications|.git|.github) beech_notifications/
          zip -r beech_notifications.zip beech_notifications

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: beech_notifications.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}